### ISSUE TITLE
How to use the new @rollup/plugin-babel with Grunt

### ISSUE THREAD

**Issue by tomlschmidt** [chrisprice/grunt-rollup#57]
#### Information 
 - Your current node version: v10.16.0
 - The package version you used: v11.1.0
 - The rollup babel plugin version: v5.0.2
 - The grunt version: v1.1.0

#### Description 
Since `rollup-plugin-babel` has been deprecated I am trying to use the new `@rollup/plugin-babel`. In their readme they suggest the use of an import statement to load the plugin but since import is not supported by node as far as I understand, it is also not possible to do so in the gruntfile. Using require doesn't work either. I get `TypeError: babel is not a function` as error message. 

How do I correctly use `@rollup/plugin-babel` with `grunt-rollup`?

#### Reproduce by 
The following is a stripped down version of my gruntfile:
```js
module.exports = function (grunt) {

	var babel = require('@rollup/plugin-babel');

	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),

		rollup: {
			options: {
				sourceMap: true,
				plugins: [
					babel({
						exclude: './node_modules/**'
					})
				]
			},
			dist: {
				files: {
					'dist/js/bundle.js': 'src/js/index.js'
				}
			}
		}

	});

	grunt.loadNpmTasks('grunt-rollup');

	grunt.registerTask('build', [
		'rollup:dist'
	]);

}
```

**Comment by GMartigny** [comment]
Hi,

Your issue is not related to this package, but thanks for bringing to my attention that `rollup-plugin-babel` has been deprecated.

Node support for ESM `import/export` statements is indeed still in development. You can enable it with [various options](https://nodejs.org/docs/v14.4.0/api/esm.html#esm_enabling), but I don't know how `grunt` will react.
When consuming ESM module with `require`, you have to specify the name to import. `@rollup/plugin-babel` export a `default` and a `babel` endpoints (which I guess are the sames).

This solves your issue:
```js
var babel = require('@rollup/plugin-babel').default;
// or
var { babel } = require('@rollup/plugin-babel');
```

> All of this is true today and will likely change in the coming month.

**Comment by tomlschmidt** [comment]
Well that makes sense and it did work indeed. Thanks for the help!
